permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 黄曦然
  email: huang@come2art.com
  link: http://reesun.github.io
  github: http://github.com/reesun

# 站点信息
title: 梦开始的地方
description: 梦开始的地方
url: http://reesun.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://image.yuntoo.com/user_thumb/dd33391770f59dd8d47824b067324f6e.jpg@!app-avatar
favicon: http://image.yuntoo.com/user_thumb/dd33391770f59dd8d47824b067324f6e.jpg@!app-avatar

# google analytics 设置
ga:
  id: UA-20652740-2
  url: blog.come2art.com

# disqus 设置
disqus:
  shortname: come2artcom
